# Generated by Django 3.1.3 on 2020-11-20 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 15, 6, 56, 28921)),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='p_4',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
