# Generated by Django 3.1.3 on 2020-11-20 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20201120_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='p_4',
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 20, 15, 7, 9, 311738)),
        ),
    ]
