# Generated by Django 3.1.3 on 2020-11-20 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20201120_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
